### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [Praneet9/Plant_Monitor#1]
hi, @Praneet9  I am a graphic artist and I would like to design a free logo for your project. I am improving my portfolio that's why I am enthusiastic to contribute. If you are interested, I will begin asap. regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by Praneet9** [comment]
@Tobaloidee  Great to see your enthusiasm! You can go ahead!

**Comment by Tobaloidee** [comment]
Hi, @Praneet9  Here's what I came up with! I hope you like it..and if you do, I will finalize the files and make a PR with it! 

- I created a logo design that is functional and represents the project very well. It is simple and meaningful that wears a tomato red color. The main design is a combination of Tomato-Sensor-Eye elements.

![plant_monitor-01](https://user-images.githubusercontent.com/36028424/56461073-40f27880-63df-11e9-87f0-9b878bdce9d6.png)


Here's how it looks like in Readme

![readme](https://user-images.githubusercontent.com/36028424/56461075-4485ff80-63df-11e9-8397-6877d8b93e26.png)

**Comment by Praneet9** [comment]
@Tobaloidee  The Logo looks cool! Just a change - remove the underscore between two words.

**Comment by Tobaloidee** [comment]
Okay, @Praneet9  Will do now! here it is..

![new-01](https://user-images.githubusercontent.com/36028424/56465071-2218d400-6429-11e9-9a16-e0ce98c0dfbb.png)

**Comment by Tobaloidee** [comment]
or you want the word PLANT green? 
![plant_monitor g-03-03](https://user-images.githubusercontent.com/36028424/56465122-301b2480-642a-11e9-8d59-e43b2b0a2a88.png)

**Comment by Tobaloidee** [comment]
what do you think @Praneet9 ?

**Comment by Praneet9** [comment]
@Tobaloidee Plant in green looks cool! Just add space between two words and make a PR.

**Comment by Tobaloidee** [comment]
Will do!

**Comment by Tobaloidee** [comment]
here's the PR #2 with the logo upload & readme update @Praneet9 . Also, you can download all the different versions & format on the link to my drive below.

[DOWNLOAD](https://drive.google.com/drive/u/0/folders/1aIdidgg2Wu7cDf-e3t6sD8TRhjoxHguK)

Thanks for accepting my contribution! best regards!

- Tobaloidee

**Comment by Praneet9** [comment]
@Tobaloidee Great Job, Thanks!

**Comment by Tobaloidee** [comment]
You are welcome! If you need logos in the future, I am just a mention away..👍😃

**Comment by Tobaloidee** [comment]
I just visited your other projects @Praneet9  Want me to design logos for them too to make it more interesting?

**Comment by Praneet9** [comment]
@Tobaloidee Thank you, you can contribute to any project you like. Smart_Editor, Docify, Voices_of_Mumbai, ECheckin are some of my good projects if you are interested.

**Comment by Tobaloidee** [comment]
I will surely do Sir! I will just open an issue whenever I finished a design for each of them.. 👍thanks Sir!

**Comment by Praneet9** [comment]
@Tobaloidee Consider me a friend. Not really a sir! :laughing: Thanks anyway! :+1:

**Comment by Tobaloidee** [comment]
Okay okay my friend!😃
